// Word data extracted from TOEIC 400 basic words (pages 12-51)
const WORDS = [
  // Pages 12-13
  {id:1,jp:"今、始めよう！",en:"B______ now!",ans:"begin",page:"12-13"},
  {id:2,jp:"私は学校で働いています。",en:"I w______ at a school.",ans:"work",page:"12-13"},
  {id:3,jp:"新しい会社",en:"a new c______",ans:"company",page:"12-13"},
  {id:4,jp:"私の注文番号は600です。",en:"My o______ number is 600.",ans:"order",page:"12-13"},
  {id:5,jp:"その会社の従業員",en:"an e______ of the company",ans:"employee",page:"12-13"},
  {id:6,jp:"情報を得る",en:"get i______",ans:"information",page:"12-13"},
  {id:7,jp:"メールを受け取る",en:"r______ an e-mail",ans:"receive",page:"12-13"},
  {id:8,jp:"そのイベントは3日間続きます。",en:"The event will l______ three days.",ans:"last",page:"12-13"},
  {id:9,jp:"助けが必要です。",en:"I n______ some help.",ans:"need",page:"12-13"},
  {id:10,jp:"旅行ガイドを読む",en:"read a t______ guide",ans:"travel",page:"12-13"},
  // Pages 14-15
  {id:11,jp:"私は自分の仕事が好きです。",en:"I like my j______.",ans:"job",page:"14-15"},
  {id:12,jp:"私は仕事を見つける必要がある。",en:"I need to f______ a job.",ans:"find",page:"14-15"},
  {id:13,jp:"私の部署には30名います。",en:"There are 30 people in my d______.",ans:"department",page:"14-15"},
  {id:14,jp:"確認させてください。",en:"L______ me check.",ans:"let",page:"14-15"},
  {id:15,jp:"博物館を訪れる",en:"v______ a museum",ans:"visit",page:"14-15"},
  {id:16,jp:"オンラインでも注文できます。",en:"You can a______ order online.",ans:"also",page:"14-15"},
  {id:17,jp:"確かではありません。",en:"I'm not s______.",ans:"sure",page:"14-15"},
  {id:18,jp:"その電車は午後8時に出発します。",en:"The train will l______ at 8 P.M.",ans:"leave",page:"14-15"},
  {id:19,jp:"彼は営業マネージャーです。",en:"He is a s______ manager.",ans:"sales",page:"14-15"},
  {id:20,jp:"私はここに引っ越してきたばかりです。",en:"I've just m______d here.",ans:"move",page:"14-15"},
  // Pages 16-17
  {id:21,jp:"彼らは昨日東京に到着しました。",en:"They a______d in Tokyo yesterday.",ans:"arrive",page:"16-17"},
  {id:22,jp:"イベントを行う",en:"h______ an event",ans:"hold",page:"16-17"},
  {id:23,jp:"私は水曜日に戻ります。",en:"I'll r______ on Wednesday.",ans:"return",page:"16-17"},
  {id:24,jp:"お店のオープン",en:"the o______ of a store",ans:"opening",page:"16-17"},
  {id:25,jp:"彼はもうすぐここに来るはずです。",en:"He should be here s______.",ans:"soon",page:"16-17"},
  {id:26,jp:"ここに署名してください。",en:"Please s______ here.",ans:"sign",page:"16-17"},
  {id:27,jp:"私はそのレストランを見つけることができました。",en:"I was a______ to find the restaurant.",ans:"able",page:"16-17"},
  {id:28,jp:"数分間あります。",en:"I have a f______ minutes.",ans:"few",page:"16-17"},
  {id:29,jp:"私はクレジットカードで支払います。",en:"I'll p______ with a credit card.",ans:"pay",page:"16-17"},
  {id:30,jp:"彼は出張中です。",en:"He is on a business t______.",ans:"trip",page:"16-17"},
  // Pages 18-19
  {id:31,jp:"なぜ車を売ったのですか。",en:"Why did you s______ your car?",ans:"sell",page:"18-19"},
  {id:32,jp:"当社はいくつかの国にオフィスがあります。",en:"We have offices in s______ countries.",ans:"several",page:"18-19"},
  {id:33,jp:"それを聞いてうれしく思います。",en:"I'm happy to h______ that.",ans:"hear",page:"18-19"},
  {id:34,jp:"私はまだオフィスにいます。",en:"I'm s______ in the office.",ans:"still",page:"18-19"},
  {id:35,jp:"あとでお電話します。",en:"I'll call you l______.",ans:"later",page:"18-19"},
  {id:36,jp:"違う店で買い物をする",en:"shop at a d______ store",ans:"different",page:"18-19"},
  {id:37,jp:"そのホテルは空港に近い。",en:"The hotel is c______ to the airport.",ans:"close",page:"18-19"},
  {id:38,jp:"私は東京のホテルに滞在しました。",en:"I s______ed at a hotel in Tokyo.",ans:"stay",page:"18-19"},
  {id:39,jp:"私はすでにその映画を見ました。",en:"I have a______ seen the movie.",ans:"already",page:"18-19"},
  {id:40,jp:"賞品を贈呈する",en:"p______ a prize",ans:"present",page:"18-19"},
  // Pages 20-21
  {id:41,jp:"工場を訪れる",en:"visit a f______",ans:"factory",page:"20-21"},
  {id:42,jp:"私はその仕事に興味があります。",en:"I am i______ in the job.",ans:"interested",page:"20-21"},
  {id:43,jp:"テーブルが布で覆われている。",en:"The table is c______ed with a cloth.",ans:"cover",page:"20-21"},
  {id:44,jp:"本を選ぶ",en:"c______ a book",ans:"choose",page:"20-21"},
  {id:45,jp:"新しいアパートに引っ越す",en:"move to a new a______",ans:"apartment",page:"20-21"},
  {id:46,jp:"彼女は書類をファイルしている。",en:"She's filing some p______s.",ans:"paper",page:"20-21"},
  {id:47,jp:"スケジュールは変更の可能性がありますのでご注意ください。",en:"Please n______ that the schedule may change.",ans:"note",page:"20-21"},
  {id:48,jp:"ランチもディナーも両方とも",en:"b______ lunch and dinner",ans:"both",page:"20-21"},
  {id:49,jp:"コーヒーか紅茶のどちらか",en:"e______ coffee or tea",ans:"either",page:"20-21"},
  {id:50,jp:"テックスもマサヤも中国語を話せません。",en:"N______ Tex nor Masaya can speak Chinese.",ans:"neither",page:"20-21"},
  // Pages 22-23
  {id:51,jp:"そのレストランは4年前にオープンしました。",en:"The restaurant opened four years a______.",ans:"ago",page:"22-23"},
  {id:52,jp:"その本はもう読み終わりましたか。",en:"Have you f______ed reading the book?",ans:"finish",page:"22-23"},
  {id:53,jp:"あなたに近々お会いできることを願っています。",en:"I h______ to see you soon.",ans:"hope",page:"22-23"},
  {id:54,jp:"計画の一部",en:"p______ of a plan",ans:"part",page:"22-23"},
  {id:55,jp:"私は水曜日に重要な会議があります。",en:"I have an i______ meeting on Wednesday.",ans:"important",page:"22-23"},
  {id:56,jp:"クーポンを郵送する",en:"m______ a coupon",ans:"mail",page:"22-23"},
  {id:57,jp:"週に一度",en:"o______ a week",ans:"once",page:"22-23"},
  {id:58,jp:"イベントは12月30日まで続きます。",en:"The event will r______ until December 30.",ans:"run",page:"22-23"},
  {id:59,jp:"傘を持ってくる",en:"b______ an umbrella",ans:"bring",page:"22-23"},
  {id:60,jp:"注文を出す",en:"p______ an order",ans:"place",page:"22-23"},
  // Pages 24-25
  {id:61,jp:"彼女は医者になりたいと願っている。",en:"She hopes to b______ a doctor.",ans:"become",page:"24-25"},
  {id:62,jp:"ご注文の準備はできていますか。",en:"Are you r______ to order?",ans:"ready",page:"24-25"},
  {id:63,jp:"当店は週末は閉まっています。",en:"Our stores are c______ on weekends.",ans:"closed",page:"24-25"},
  {id:64,jp:"部屋に入る",en:"e______ a room",ans:"enter",page:"24-25"},
  {id:65,jp:"明日何が起きますか。",en:"What will h______ tomorrow?",ans:"happen",page:"24-25"},
  {id:66,jp:"顧客サービス",en:"c______ service",ans:"customer",page:"24-25"},
  {id:67,jp:"過去3年間に渡って",en:"over the p______ three years",ans:"past",page:"24-25"},
  {id:68,jp:"私たちは同じ大学に通っていた。",en:"We went to the s______ university.",ans:"same",page:"24-25"},
  {id:69,jp:"早く来てくださってありがとうございます。",en:"Thanks for coming e______.",ans:"early",page:"24-25"},
  {id:70,jp:"会社に加わる",en:"j______ a company",ans:"join",page:"24-25"},
  // Pages 26-27
  {id:71,jp:"会社を辞めることに決めました。",en:"I d______d to leave the company.",ans:"decide",page:"26-27"},
  {id:72,jp:"彼は庭で植物に水をやっている。",en:"He's watering p______s in a garden.",ans:"plant",page:"26-27"},
  {id:73,jp:"加藤さんを喜んで歓迎いたします。",en:"We are p______ to welcome Mr. Kato.",ans:"pleased",page:"26-27"},
  {id:74,jp:"その部屋は大きさが十分ではありません。",en:"The room is not big e______.",ans:"enough",page:"26-27"},
  {id:75,jp:"映画を観に行く",en:"go to see a f______",ans:"film",page:"26-27"},
  {id:76,jp:"その場合には",en:"in that c______",ans:"case",page:"26-27"},
  {id:77,jp:"食事をとる",en:"eat a m______",ans:"meal",page:"26-27"},
  {id:78,jp:"営業チームの誰か",en:"s______ from the sales team",ans:"someone",page:"26-27"},
  {id:79,jp:"テックスはいつも仕事に遅刻している。",en:"Tex is a______ late for work.",ans:"always",page:"26-27"},
  {id:80,jp:"彼女は1枚の紙を持っている。",en:"She's holding a p______ of paper.",ans:"piece",page:"26-27"},
  // Pages 28-29
  {id:81,jp:"私はいつもペンを持ち歩いています。",en:"I always c______ a pen with me.",ans:"carry",page:"28-29"},
  {id:82,jp:"注文品を出荷する",en:"s______ an order",ans:"ship",page:"28-29"},
  {id:83,jp:"あなたに連絡を取ろうとしていました。",en:"I've been trying to r______ you.",ans:"reach",page:"28-29"},
  {id:84,jp:"彼女に会ったことは覚えています。",en:"I r______ seeing her.",ans:"remember",page:"28-29"},
  {id:85,jp:"薬の分野で",en:"in the f______ of medicine",ans:"field",page:"28-29"},
  {id:86,jp:"ベジタリアン向けの料理はありますか。",en:"Do you have any vegetarian d______es?",ans:"dish",page:"28-29"},
  {id:87,jp:"インターネットに写真を投稿する",en:"p______ pictures on the Internet",ans:"post",page:"28-29"},
  {id:88,jp:"それはいいですね（いいように思える）",en:"That s______s great.",ans:"sound",page:"28-29"},
  {id:89,jp:"昼食休憩を取りましょう。",en:"Let's take a lunch b______.",ans:"break",page:"28-29"},
  {id:90,jp:"コピー機が壊れているようです。",en:"The copy machine s______s to be broken.",ans:"seem",page:"28-29"},
  // Pages 30-31
  {id:91,jp:"学校を建てる",en:"b______ a school",ans:"build",page:"30-31"},
  {id:92,jp:"必要な部品を注文する",en:"order the n______ parts",ans:"necessary",page:"30-31"},
  {id:93,jp:"信じられません。",en:"I can't b______ it.",ans:"believe",page:"30-31"},
  {id:94,jp:"我々のビジネスは成長しています。",en:"Our business is g______ing.",ans:"grow",page:"30-31"},
  {id:95,jp:"でも、確かではありません。",en:"I'm not sure, t______.",ans:"though",page:"30-31"},
  {id:96,jp:"テックス社はどんな種類の会社ですか。",en:"What k______ of business is Tex Corporation?",ans:"kind",page:"30-31"},
  {id:97,jp:"私は電車を逃した。",en:"I m______ed the train.",ans:"miss",page:"30-31"},
  {id:98,jp:"休暇はどのように過ごしましたか。",en:"How did you s______ your vacation?",ans:"spend",page:"30-31"},
  {id:99,jp:"私はとても忙しい。",en:"I'm very b______.",ans:"busy",page:"30-31"},
  {id:100,jp:"時間とお金を節約する",en:"s______ time and money",ans:"save",page:"30-31"},
  // Pages 32-33
  {id:101,jp:"地図を見つける",en:"find a m______",ans:"map",page:"32-33"},
  {id:102,jp:"数人が自転車に乗っている。",en:"Some people are r______ing bicycles.",ans:"ride",page:"32-33"},
  {id:103,jp:"もう少しで終わります。",en:"I'm a______ done.",ans:"almost",page:"32-33"},
  {id:104,jp:"スポーツ用品を買う",en:"buy sporting g______",ans:"goods",page:"32-33"},
  {id:105,jp:"すばやく仕事を終える",en:"finish work q______",ans:"quickly",page:"32-33"},
  {id:106,jp:"ドアはどのくらい幅広いですか。",en:"How w______ is the door?",ans:"wide",page:"32-33"},
  {id:107,jp:"彼は有名なミュージシャン。",en:"He is a f______ musician.",ans:"famous",page:"32-33"},
  {id:108,jp:"私のアパートは停電しています。",en:"The p______ is out in my apartment.",ans:"power",page:"32-33"},
  {id:109,jp:"ホテルの部屋を予約する",en:"b______ a hotel room",ans:"book",page:"32-33"},
  {id:110,jp:"名前が間違っています。",en:"The name is w______.",ans:"wrong",page:"32-33"},
  // Pages 34-35
  {id:111,jp:"私は昨日、その劇を観ました。",en:"I saw the p______ last night.",ans:"play",page:"34-35"},
  {id:112,jp:"今日は普段より忙しかった。",en:"We were busier than u______ today.",ans:"usual",page:"34-35"},
  {id:113,jp:"あなたがそれを気に入ると確信しています。",en:"I am c______ you will like it.",ans:"certain",page:"34-35"},
  {id:114,jp:"この本は理解するのが難しい。",en:"This book is d______ to understand.",ans:"difficult",page:"34-35"},
  {id:115,jp:"戸棚にファイルを保管する",en:"s______ files in a cabinet",ans:"store",page:"34-35"},
  {id:116,jp:"彼の答えははっきりしていた。",en:"His answer was c______.",ans:"clear",page:"34-35"},
  {id:117,jp:"ドアにカギをかけるのを忘れないでください。",en:"Don't f______ to lock the door.",ans:"forget",page:"34-35"},
  {id:118,jp:"売り上げは昨年20%上がった。",en:"Sales r______ 20 percent last year.",ans:"rise",page:"34-35"},
  {id:119,jp:"機会があれば",en:"if you get a c______",ans:"chance",page:"34-35"},
  {id:120,jp:"女性が絵を描いている。",en:"A woman is d______ing a picture.",ans:"draw",page:"34-35"},
  // Pages 36-37
  {id:121,jp:"それを聞いてうれしいです。",en:"I'm g______ to hear that.",ans:"glad",page:"36-37"},
  {id:122,jp:"私の部屋は暖かすぎる。",en:"My room is too w______.",ans:"warm",page:"36-37"},
  {id:123,jp:"この件に関するご質問",en:"questions about this m______",ans:"matter",page:"36-37"},
  {id:124,jp:"役立つ情報",en:"u______ information",ans:"useful",page:"36-37"},
  {id:125,jp:"カタログを参照する",en:"r______ to a catalog",ans:"refer",page:"36-37"},
  {id:126,jp:"そのホテルは安全な地域にあります。",en:"The hotel is in a s______ area.",ans:"safe",page:"36-37"},
  {id:127,jp:"ルールは単純です。",en:"The rules are s______.",ans:"simple",page:"36-37"},
  {id:128,jp:"間違いを発見する",en:"d______ an error",ans:"discover",page:"36-37"},
  {id:129,jp:"数台の車が通りに停まっている。",en:"Some cars are p______ed along the street.",ans:"park",page:"36-37"},
  {id:130,jp:"男性は何をすることを約束していますか。",en:"What does the man p______ to do?",ans:"promise",page:"36-37"},
  // Pages 38-39
  {id:131,jp:"私は自分の会社を誇りに思います。",en:"I'm p______ of my company.",ans:"proud",page:"38-39"},
  {id:132,jp:"私はかなり忙しい。",en:"I'm p______ busy.",ans:"pretty",page:"38-39"},
  {id:133,jp:"大きな騒音を立てる",en:"make a lot of n______",ans:"noise",page:"38-39"},
  {id:134,jp:"たぶん、私たちは会ったことがあります。",en:"P______, we've met before.",ans:"perhaps",page:"38-39"},
  {id:135,jp:"農場労働者",en:"f______ workers",ans:"farm",page:"38-39"},
  {id:136,jp:"製品を買う",en:"buy a p______",ans:"product",page:"38-39"},
  {id:137,jp:"お客様をイベントに招待する",en:"i______ customers to an event",ans:"invite",page:"38-39"},
  {id:138,jp:"女性は何をすることを申し出ていますか。",en:"What does the woman o______ to do?",ans:"offer",page:"38-39"},
  {id:139,jp:"お客様に情報を提供する",en:"p______ customers with information",ans:"provide",page:"38-39"},
  {id:140,jp:"その価格は朝食を含んでいます。",en:"The price i______s breakfast.",ans:"include",page:"38-39"},
  // Pages 40-41
  {id:141,jp:"営業報告書",en:"a sales r______",ans:"report",page:"40-41"},
  {id:142,jp:"何が問題ですか。",en:"What is the p______?",ans:"problem",page:"40-41"},
  {id:143,jp:"男性はおそらく何をしている人ですか。",en:"Who most l______ is the man?",ans:"likely",page:"40-41"},
  {id:144,jp:"情報を求める",en:"r______ information",ans:"request",page:"40-41"},
  {id:145,jp:"チケットはいくら掛かりますか。",en:"How much does a ticket c______?",ans:"cost",page:"40-41"},
  {id:146,jp:"全ての仕事を完了させる",en:"c______ all the work",ans:"complete",page:"40-41"},
  {id:147,jp:"用紙に記入する",en:"fill out a f______",ans:"form",page:"40-41"},
  {id:148,jp:"3年の経験",en:"three years of e______",ans:"experience",page:"40-41"},
  {id:149,jp:"私はその会議に参加します。",en:"I will a______ the meeting.",ans:"attend",page:"40-41"},
  {id:150,jp:"予定の変更を発表する",en:"a______ a schedule change",ans:"announce",page:"40-41"},
  // Pages 42-43
  {id:151,jp:"私はその職に興味があります。",en:"I am interested in the p______.",ans:"position",page:"42-43"},
  {id:152,jp:"彼は修理店で働いている。",en:"He's working in a r______ shop.",ans:"repair",page:"42-43"},
  {id:153,jp:"地元の新聞",en:"a l______ newspaper",ans:"local",page:"42-43"},
  {id:154,jp:"イベントの目的は何ですか。",en:"What is the p______ of the event?",ans:"purpose",page:"42-43"},
  {id:155,jp:"プロジェクトについて話し合う",en:"d______ a project",ans:"discuss",page:"42-43"},
  {id:156,jp:"価格は上がると予期されています。",en:"Prices are e______ed to rise.",ans:"expect",page:"42-43"},
  {id:157,jp:"我々の売り上げは今年増えました。",en:"Our sales have i______d this year.",ans:"increase",page:"42-43"},
  {id:158,jp:"話し手は何を述べていますか。",en:"What does the speaker m______?",ans:"mention",page:"42-43"},
  {id:159,jp:"工場見学",en:"a factory t______",ans:"tour",page:"42-43"},
  {id:160,jp:"無料で",en:"free of c______",ans:"charge",page:"42-43"},
  // Pages 44-45
  {id:161,jp:"20%割引",en:"a 20 percent d______",ans:"discount",page:"44-45"},
  {id:162,jp:"調査プロジェクト",en:"a r______ project",ans:"research",page:"44-45"},
  {id:163,jp:"新しいスタッフを雇う",en:"h______ new staff",ans:"hire",page:"44-45"},
  {id:164,jp:"私は少し前に新しいプリンターを買いました。",en:"I r______ bought a new printer.",ans:"recently",page:"44-45"},
  {id:165,jp:"イベントの主な目的",en:"the m______ purpose of the event",ans:"main",page:"44-45"},
  {id:166,jp:"銀行口座を開きたいと思います。",en:"I'd like to open a bank a______.",ans:"account",page:"44-45"},
  {id:167,jp:"国際的な会社",en:"an i______ company",ans:"international",page:"44-45"},
  {id:168,jp:"雑誌を1部受け取る",en:"receive a c______ of a magazine",ans:"copy",page:"44-45"},
  {id:169,jp:"男性はおそらくどこで働いていますか。",en:"Where does the man p______ work?",ans:"probably",page:"44-45"},
  {id:170,jp:"注文の手続き",en:"the ordering p______",ans:"process",page:"44-45"},
  // Pages 46-47
  {id:171,jp:"結果として",en:"as a r______",ans:"result",page:"46-47"},
  {id:172,jp:"会社の社長",en:"company p______",ans:"president",page:"46-47"},
  {id:173,jp:"材料費",en:"the cost of the m______s",ans:"material",page:"46-47"},
  {id:174,jp:"その注文の記録はありません。",en:"There is no r______ of that order.",ans:"record",page:"46-47"},
  {id:175,jp:"職に応募する",en:"a______ for a position",ans:"apply",page:"46-47"},
  {id:176,jp:"詳細は当社のウェブサイトをご覧ください。",en:"For more d______s, visit our Web site.",ans:"detail",page:"46-47"},
  {id:177,jp:"部屋の料金",en:"room r______s",ans:"rate",page:"46-47"},
  {id:178,jp:"音楽業界",en:"the music i______",ans:"industry",page:"46-47"},
  {id:179,jp:"公共の図書館",en:"a p______ library",ans:"public",page:"46-47"},
  {id:180,jp:"まだ彼に頼んでいません。",en:"I haven't asked him y______.",ans:"yet",page:"46-47"},
  // Pages 48-49
  {id:181,jp:"その絵を買うことは可能ですか。",en:"Is it p______ to buy the painting?",ans:"possible",page:"48-49"},
  {id:182,jp:"彼らは家具を動かしている。",en:"They're moving some f______.",ans:"furniture",page:"48-49"},
  {id:183,jp:"出張の手配をする",en:"a______ a business trip",ans:"arrange",page:"48-49"},
  {id:184,jp:"何についての通知ですか。",en:"What is the n______ about?",ans:"notice",page:"48-49"},
  {id:185,jp:"アカウントを作る",en:"c______ an account",ans:"create",page:"48-49"},
  {id:186,jp:"正午にランチが出されます。",en:"Lunch will be s______d at noon.",ans:"serve",page:"48-49"},
  {id:187,jp:"イベントに向けて準備をする",en:"p______ for an event",ans:"prepare",page:"48-49"},
  {id:188,jp:"休暇規定",en:"vacation p______",ans:"policy",page:"48-49"},
  {id:189,jp:"小包を送る",en:"send a p______",ans:"package",page:"48-49"},
  {id:190,jp:"旅行代理店を探す",en:"look for a travel a______",ans:"agency",page:"48-49"},
  // Pages 50-51
  {id:191,jp:"加藤さんを紹介させてください。",en:"Let me i______ Mr. Kato.",ans:"introduce",page:"50-51"},
  {id:192,jp:"チケットを予約する",en:"r______ a ticket",ans:"reserve",page:"50-51"},
  {id:193,jp:"社員が自宅で仕事をすることを許す",en:"a______ employees to work from home",ans:"allow",page:"50-51"},
  {id:194,jp:"詳しくは、1番を押してください。",en:"For more information, please p______ one.",ans:"press",page:"50-51"},
  {id:195,jp:"明日は天気が良いでしょう。",en:"The w______ will be nice tomorrow.",ans:"weather",page:"50-51"},
  {id:196,jp:"ご支援ありがとうございます。",en:"Thank you for your s______.",ans:"support",page:"50-51"},
  {id:197,jp:"その本は5月に出版された。",en:"The book was p______ed in May.",ans:"publish",page:"50-51"},
  {id:198,jp:"地元のイベントを説明する",en:"d______ a local event",ans:"describe",page:"50-51"},
  {id:199,jp:"リストに名前を加える",en:"a______ a name to a list",ans:"add",page:"50-51"},
  {id:200,jp:"注文品を配達する",en:"d______ an order",ans:"deliver",page:"50-51"},
];
